version: '3.2'
networks:
  default:
    external:
      name: "localstack"
services:
  localstack:
    container_name: ${LOCALSTACK_DOCKER_NAME-localstack_main}
    image: localstack/localstack-full
    network_mode: bridge
    ports:
      - 8080:8080
      - 4566:4566
      - 4574:4574 #lambda
    environment:
      - DEBUG=1
      - SERVICES=apigateway,lambda
      - DEFAULT_REGION=us-west-1
      - LAMBDA_EXECUTOR=local
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
